# Generated by Django 2.1.2 on 2018-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181020_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='main',
            field=models.BooleanField(default=0),
        ),
    ]
