# Generated by Django 2.1.2 on 2018-10-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_new_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='main',
            field=models.BooleanField(),
        ),
    ]
